name: {{cookiecutter.package_name}}
dependencies:
  - python=3.8
  - matplotlib-base
  # pandas, numpy, scipy
  - click
  - pyyaml
  - h5py
  - tqdm
  - fastai::opencv-python-headless
  - conda-forge::pytorch-lightning>=1.5.1
  - pytorch::torchvision
  - pytorch::pytorch=1.10
  - tensorboardx
  - sphinx
  - pip
  - pip:
    - pytest
    - flake8
    - rope
    - autopep8
    - torchsummary
    - -e .  # install package in development mode
