name: {{cookiecutter.package_name}}
dependencies:
  - python=3.8
  - matplotlib-base
  - pandas
  - pytest
  - flake8
  - rope
  - autopep8
  - click
  - pyyaml
  - h5py
  - tqdm
  - fastai::opencv-python-headless
  - conda-forge::pytorch-lightning>=1.5.1
  - pytorch::torchvision
  - pytorch::pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
  - tensorboardx
  - pip
  - pip:
    - torchsummary
    - -e .  # install package in development mode
