# Filename: logging.yml
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s, %(levelname)8s, %(name)s, %(message)s"
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: error.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8

root:
    level: INFO
    handlers: [debug_file_handler]
